/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es/components/alert/index.mjs')['ElAlert']
    ElAside: typeof import('element-plus/es/components/container/index.mjs')['ElAside']
    ElButton: typeof import('element-plus/es/components/button/index.mjs')['ElButton']
    ElCard: typeof import('element-plus/es/components/card/index.mjs')['ElCard']
    ElCheckbox: typeof import('element-plus/es/components/checkbox/index.mjs')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es/components/checkbox/index.mjs')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es/components/collapse/index.mjs')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es/components/collapse/index.mjs')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es/components/container/index.mjs')['ElContainer']
    ElDescriptions: typeof import('element-plus/es/components/descriptions/index.mjs')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es/components/descriptions/index.mjs')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es/components/dialog/index.mjs')['ElDialog']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es/components/empty/index.mjs')['ElEmpty']
    ElFooter: typeof import('element-plus/es/components/container/index.mjs')['ElFooter']
    ElForm: typeof import('element-plus/es/components/form/index.mjs')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index.mjs')['ElFormItem']
    ElHeader: typeof import('element-plus/es/components/container/index.mjs')['ElHeader']
    ElInput: typeof import('element-plus/es/components/input/index.mjs')['ElInput']
    ElInputNumber: typeof import('element-plus/es/components/input-number/index.mjs')['ElInputNumber']
    ElMain: typeof import('element-plus/es/components/container/index.mjs')['ElMain']
    ElMenu: typeof import('element-plus/es/components/menu/index.mjs')['ElMenu']
    ElMenuItem: typeof import('element-plus/es/components/menu/index.mjs')['ElMenuItem']
    ElOption: typeof import('element-plus/es/components/select/index.mjs')['ElOption']
    ElPagination: typeof import('element-plus/es/components/pagination/index.mjs')['ElPagination']
    ElSelect: typeof import('element-plus/es/components/select/index.mjs')['ElSelect']
    ElSubMenu: typeof import('element-plus/es/components/menu/index.mjs')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es/components/switch/index.mjs')['ElSwitch']
    ElTable: typeof import('element-plus/es/components/table/index.mjs')['ElTable']
    ElTableColumn: typeof import('element-plus/es/components/table/index.mjs')['ElTableColumn']
    ElTag: typeof import('element-plus/es/components/tag/index.mjs')['ElTag']
    EventTimeline: typeof import('./components/EventTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starfield: typeof import('./components/landing/Starfield.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es/components/loading/index.mjs')['ElLoadingDirective']
  }
}
